### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws#19]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by juhoaws** [comment]
This is now fixed and tested with the automated suggested pull requests

**Comment by vprince1** [comment]
I still see a bunch of references to the old version. Is it possible to update them? Thanks

![image](https://github.com/aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws/assets/11996632/7652c2c3-0f75-4fbb-a8dd-c0c62cc71f39)

**Comment by juhoaws** [comment]
Ah, ok. I didn't realize dependabot failed to provide the correct version, will look into updating to the alpha

**Comment by juhoaws** [comment]
Fixed again

**Comment by juhoaws** [comment]
I believe this is a different package that contains the types for babel/traverse. I'm not sure if it's within the vulnerability scope?

**Comment by vprince1** [comment]
got it.. thx..
