### ISSUE TITLE
IdentityComponentLoggingBucket of CustomIdentityComponent stores access log to itself.

### ISSUE THREAD

**Issue by junsjang** [aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws#29]
The bucket has serverAccessLogsPrefix without serverAccessLogsBucket.
This will make s3.Bucket construct to specify the bucket itself as an access log bucket and it will always generate access log by make a access log file.
You can see the implementation from https://github.com/aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws/blob/61ae1fa46350c96556012ea18282d6542326110a/CustomIdentityComponent/lib/custom_identity_component-stack.ts#L76.
This will make huge number of access log file even there is no actual accessing.

The logging bucket is used only as a logging purpose, we can omit the access log configuration, so that it not create meaning less access log files.

**Comment by juhoaws** [comment]
Great find, thank you for pointing this out! It's not fixed in the latest commit

**Comment by juhoaws** [comment]
Fix pushed.
