### ISSUE TITLE
Log Groups for the Custom Identity Stack should have an expiration

### ISSUE THREAD

**Issue by BMorinDrifter** [aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws#8]
Cloudwatch log groups by default never expire, potentially leaving a land mine where customers can accumulate a storage bill over months.  This also increases exposure to legal liability for anything that might be in those logs (intentional or by accident.)

Suggest a default of 30 or 90 days to mitigate.

**Comment by juhoaws** [comment]
Addressed with [this commit ](https://github.com/aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws/commit/549c0f7e9bd2303a5cb55f61a77a7f68069c509b).

Required us to use the custom resource based approach to log settings which generates extra Lambdas that set log retention covering edge cases as well.
